raw_image_topic: "/image_raw"
event_topic: "/davis/left/events"
imu_topic: "/mavros/imu/data"
depth_topic: "/camera/depth/image_rect_raw"
odometry_topic: "/vicon_imu_ekf_odom"
      
# raw_image_topic: "/davis_left/image_raw"
# event_topic: "/davis/left/events"
# imu_topic: "/davis_left/imu"
# radar_topic: "/ti_mmwave/radar_scan_pcl"
# odometry_topic: "/davis_left/imu"
# camera_info_topic: "/davis_left/camera_info"